version: '3'

networks:
  wai:

services:
  mysql:
    image: mysql:5.7.30
    container_name: wai_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql # necessario se il restart è uguale ad unless-stopped
    environment:
      MYSQL_DATABASE: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: aa
      MYSQL_ROOT_PASSWORD: aa
    networks:
      - wai
  php:
    container_name: wai_php_apache
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./wai:/var/www/wai
      - ./include:/var/www/include
      - ./apache/default.conf:/etc/apache2/sites-available/000-default.conf # per creare i virtualhost sovrascriviamo il default.conf
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    ports:
      - "9000:9000"
      - "8081:80"
    networks:
      - wai
# Una volta eseguito il container cambiare i permessi della cartella wai e include con il comando
# sudo chown -R <user>:33 wai/  
# sudo chown -R <user>:33 include/  
# Dove <user> è l'utente del vostro pc (x modificare i file) e 33 è l'id dell'utente www-data (per farlo eseguire all'apache del docker)