version: '3'

networks:
  wai:

services:
  mysql:
    image: mysql:5.7.30
    container_name: wai_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql # necessario se il restart è uguale ad unless-stopped
    environment:
      MYSQL_DATABASE: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: aa
      MYSQL_ROOT_PASSWORD: aa
    networks:
      - wai
  php:
    container_name: wai_php_apache
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/wai
      - ./apache/default.conf:/etc/apache2/sites-available/000-default.conf # per creare i virtualhost sovrascriviamo il default.conf
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    ports:
      - "9000:9000"
      - "8081:80"
    networks:
      - wai